name: Build Custom M3U

on:
  workflow_run:
    workflows: ["Auto Pluto Update"]   # MUSS exakt so heißen wie in auto.yml
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Script ausführen
        run: node scripts/build_m3u.js

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add -f plutotv_de_custom.m3u8
          git commit -m "Auto build M3U" || echo "Keine Änderungen"
          git push origin HEAD:main || echo "Nichts zu pushen"
